name: update-chart-build

on:
  issues:
    branches: [master, workflows]
    types: [labeled]
  pull_request:
    branches: [master, workflows]
    types: [labeled]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
        
      - name: extractsvg
        run: npm run extractsvg strict

      - name: readmepreview
        run: npm run readmepreview
